---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: mydep-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: indexedjobs
  childResources:
    - apiVersion: v1
      resource: pods
  hooks:
    sync:
      webhook:
        url: http://mydep-controller.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep-controller
  template:
    metadata:
      labels:
        app: mydep-controller
    spec:
      containers:
      - name: controller
        image: python:3.11
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: mydep-controller
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-controller
  namespace: metacontroller
spec:
  selector:
    app: mydep-controller
  ports:
  - port: 80
