---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mydeps.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  scope: Namespaced
  names:
    plural: mydeps
    singular: mydep
    kind: MyDep
    
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}